// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top,hls_ip_2014_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.907250,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}" *)

module top (
        ap_clk,
        ap_rst,
        cfg_req_V,
        cfg_req_V_ap_vld,
        cfg_req_V_ap_ack,
        cfg_resp_V,
        cfg_resp_V_ap_vld,
        cfg_resp_V_ap_ack,
        g_itu_iface_req_V,
        g_itu_iface_req_V_ap_vld,
        g_itu_iface_req_V_ap_ack,
        g_itu_iface_resp_V,
        g_itu_iface_resp_V_ap_vld,
        g_itu_iface_resp_V_ap_ack
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 1'b0;
parameter    ap_ST_st2_fsm_1 = 1'b1;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv33_1ABCDABCD = 33'b110101011110011011010101111001101;
parameter    ap_const_lv33_100000000 = 33'b100000000000000000000000000000000;
parameter    ap_const_lv33_0 = 33'b000000000000000000000000000000000;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv5_2 = 5'b10;
parameter    ap_const_lv5_3 = 5'b11;
parameter    ap_const_lv5_4 = 5'b100;
parameter    ap_const_lv5_5 = 5'b101;
parameter    ap_const_lv32_45 = 32'b1000101;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_40 = 32'b1000000;
parameter    ap_const_lv32_44 = 32'b1000100;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv32_22 = 32'b100010;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv24_0 = 24'b000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input  [69:0] cfg_req_V;
input   cfg_req_V_ap_vld;
output   cfg_req_V_ap_ack;
output  [32:0] cfg_resp_V;
output   cfg_resp_V_ap_vld;
input   cfg_resp_V_ap_ack;
output  [96:0] g_itu_iface_req_V;
output   g_itu_iface_req_V_ap_vld;
input   g_itu_iface_req_V_ap_ack;
input  [32:0] g_itu_iface_resp_V;
input   g_itu_iface_resp_V_ap_vld;
output   g_itu_iface_resp_V_ap_ack;

reg cfg_req_V_ap_ack;
reg cfg_resp_V_ap_vld;
reg[96:0] g_itu_iface_req_V;
reg g_itu_iface_req_V_ap_vld;
reg g_itu_iface_resp_V_ap_ack;
reg   [15:0] s_first_ds_id_V = 16'b0000000000000000;
reg   [15:0] s_first_index_V = 16'b0000000000000000;
reg   [15:0] s_last_ds_id_V = 16'b0000000000000000;
reg   [15:0] s_last_index_V = 16'b0000000000000000;
reg   [2:0] s_pred_V = 3'b000;
wire   [0:0] tmp_1_fu_140_p3;
reg   [0:0] tmp_1_reg_313;
reg   [0:0] ap_CS_fsm = 1'b0;
wire   [0:0] tmp_2_fu_168_p2;
reg    ap_sig_bdd_43;
reg    ap_sig_ioackin_g_itu_iface_req_V_ap_ack;
reg   [0:0] tmp_2_reg_320;
reg   [15:0] s_last_ds_id_V_load_reg_324;
reg   [15:0] s_last_index_V_load_reg_330;
wire   [6:0] tmp_8_fu_251_p1;
reg   [6:0] tmp_8_reg_336;
wire   [0:0] tmp_5_i_fu_255_p2;
reg   [0:0] tmp_5_i_reg_342;
reg   [32:0] p_0173_1_phi_fu_127_p6;
reg   [32:0] p_0173_1_reg_122;
reg    ap_sig_bdd_77;
reg    ap_sig_ioackin_cfg_resp_V_ap_ack;
wire   [4:0] raddr_V_fu_158_p4;
wire   [96:0] r_V_fu_246_p1;
wire   [96:0] req_V_2_fu_278_p3;
wire   [96:0] req_V_1_fu_304_p3;
reg    ap_reg_ioackin_g_itu_iface_req_V_ap_ack = 1'b0;
reg    ap_reg_ioackin_cfg_resp_V_ap_ack = 1'b0;
wire   [79:0] tmp_fu_234_p5;
wire   [79:0] tmp_6_fu_261_p7;
wire   [95:0] tmp_7_fu_274_p1;
wire   [79:0] tmp_5_fu_287_p7;
wire   [95:0] tmp_3_fu_300_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_sig_bdd_248;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_cfg_resp_V_ap_ack assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_cfg_resp_V_ap_ack
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_cfg_resp_V_ap_ack <= ap_const_logic_0;
    end else begin
        if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
            if (~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342)) | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack))) begin
                ap_reg_ioackin_cfg_resp_V_ap_ack <= ap_const_logic_0;
            end else if (ap_sig_bdd_248) begin
                ap_reg_ioackin_cfg_resp_V_ap_ack <= ap_const_logic_1;
            end
        end
    end
end

/// ap_reg_ioackin_g_itu_iface_req_V_ap_ack assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_g_itu_iface_req_V_ap_ack
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_g_itu_iface_req_V_ap_ack <= ap_const_logic_0;
    end else begin
        if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)))) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342)) | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack))) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342)) | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack))))) begin
            ap_reg_ioackin_g_itu_iface_req_V_ap_ack <= ap_const_logic_0;
        end else if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_1 == g_itu_iface_req_V_ap_ack) & ~ap_sig_bdd_43) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342) & (ap_const_logic_1 == g_itu_iface_req_V_ap_ack) & ~ap_sig_bdd_77) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342) & (ap_const_logic_1 == g_itu_iface_req_V_ap_ack) & ~ap_sig_bdd_77))) begin
            ap_reg_ioackin_g_itu_iface_req_V_ap_ack <= ap_const_logic_1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & (tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))))) begin
        p_0173_1_reg_122[0] <= 1'b0;
        p_0173_1_reg_122[2] <= 1'b0;
        p_0173_1_reg_122[3] <= 1'b0;
        p_0173_1_reg_122[6] <= 1'b0;
        p_0173_1_reg_122[7] <= 1'b0;
        p_0173_1_reg_122[8] <= 1'b0;
        p_0173_1_reg_122[9] <= 1'b0;
        p_0173_1_reg_122[11] <= 1'b0;
        p_0173_1_reg_122[13] <= 1'b0;
        p_0173_1_reg_122[15] <= 1'b0;
        p_0173_1_reg_122[16] <= 1'b0;
        p_0173_1_reg_122[18] <= 1'b0;
        p_0173_1_reg_122[19] <= 1'b0;
        p_0173_1_reg_122[22] <= 1'b0;
        p_0173_1_reg_122[23] <= 1'b0;
        p_0173_1_reg_122[24] <= 1'b0;
        p_0173_1_reg_122[25] <= 1'b0;
        p_0173_1_reg_122[27] <= 1'b0;
        p_0173_1_reg_122[29] <= 1'b0;
        p_0173_1_reg_122[31] <= 1'b0;
        p_0173_1_reg_122[32] <= 1'b0;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_168_p2) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))))) begin
        p_0173_1_reg_122[0] <= 1'b0;
        p_0173_1_reg_122[2] <= 1'b0;
        p_0173_1_reg_122[3] <= 1'b0;
        p_0173_1_reg_122[6] <= 1'b0;
        p_0173_1_reg_122[7] <= 1'b0;
        p_0173_1_reg_122[8] <= 1'b0;
        p_0173_1_reg_122[9] <= 1'b0;
        p_0173_1_reg_122[11] <= 1'b0;
        p_0173_1_reg_122[13] <= 1'b0;
        p_0173_1_reg_122[15] <= 1'b0;
        p_0173_1_reg_122[16] <= 1'b0;
        p_0173_1_reg_122[18] <= 1'b0;
        p_0173_1_reg_122[19] <= 1'b0;
        p_0173_1_reg_122[22] <= 1'b0;
        p_0173_1_reg_122[23] <= 1'b0;
        p_0173_1_reg_122[24] <= 1'b0;
        p_0173_1_reg_122[25] <= 1'b0;
        p_0173_1_reg_122[27] <= 1'b0;
        p_0173_1_reg_122[29] <= 1'b0;
        p_0173_1_reg_122[31] <= 1'b0;
        p_0173_1_reg_122[32] <= 1'b1;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342)) | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack)))) begin
        p_0173_1_reg_122[0] <= 1'b1;
        p_0173_1_reg_122[2] <= 1'b1;
        p_0173_1_reg_122[3] <= 1'b1;
        p_0173_1_reg_122[6] <= 1'b1;
        p_0173_1_reg_122[7] <= 1'b1;
        p_0173_1_reg_122[8] <= 1'b1;
        p_0173_1_reg_122[9] <= 1'b1;
        p_0173_1_reg_122[11] <= 1'b1;
        p_0173_1_reg_122[13] <= 1'b1;
        p_0173_1_reg_122[15] <= 1'b1;
        p_0173_1_reg_122[16] <= 1'b1;
        p_0173_1_reg_122[18] <= 1'b1;
        p_0173_1_reg_122[19] <= 1'b1;
        p_0173_1_reg_122[22] <= 1'b1;
        p_0173_1_reg_122[23] <= 1'b1;
        p_0173_1_reg_122[24] <= 1'b1;
        p_0173_1_reg_122[25] <= 1'b1;
        p_0173_1_reg_122[27] <= 1'b1;
        p_0173_1_reg_122[29] <= 1'b1;
        p_0173_1_reg_122[31] <= 1'b1;
        p_0173_1_reg_122[32] <= 1'b1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_168_p2) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))) & (raddr_V_fu_158_p4 == ap_const_lv5_1))) begin
        s_first_ds_id_V <= {{cfg_req_V[ap_const_lv32_2F : ap_const_lv32_20]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_168_p2) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))) & (raddr_V_fu_158_p4 == ap_const_lv5_2))) begin
        s_first_index_V <= {{cfg_req_V[ap_const_lv32_2F : ap_const_lv32_20]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_168_p2) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))) & (raddr_V_fu_158_p4 == ap_const_lv5_3))) begin
        s_last_ds_id_V <= {{cfg_req_V[ap_const_lv32_2F : ap_const_lv32_20]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))))) begin
        s_last_ds_id_V_load_reg_324 <= s_last_ds_id_V;
        s_last_index_V_load_reg_330 <= s_last_index_V;
        tmp_5_i_reg_342 <= tmp_5_i_fu_255_p2;
        tmp_8_reg_336 <= tmp_8_fu_251_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_168_p2) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))) & (raddr_V_fu_158_p4 == ap_const_lv5_4))) begin
        s_last_index_V <= {{cfg_req_V[ap_const_lv32_2F : ap_const_lv32_20]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_168_p2) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))) & (raddr_V_fu_158_p4 == ap_const_lv5_5))) begin
        s_pred_V <= {{cfg_req_V[ap_const_lv32_22 : ap_const_lv32_20]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))))) begin
        tmp_1_reg_313 <= cfg_req_V[ap_const_lv32_45];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))))) begin
        tmp_2_reg_320 <= tmp_2_fu_168_p2;
    end
end

/// ap_sig_ioackin_cfg_resp_V_ap_ack assign process. ///
always @ (cfg_resp_V_ap_ack or ap_reg_ioackin_cfg_resp_V_ap_ack)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_cfg_resp_V_ap_ack)) begin
        ap_sig_ioackin_cfg_resp_V_ap_ack = cfg_resp_V_ap_ack;
    end else begin
        ap_sig_ioackin_cfg_resp_V_ap_ack = ap_const_logic_1;
    end
end

/// ap_sig_ioackin_g_itu_iface_req_V_ap_ack assign process. ///
always @ (g_itu_iface_req_V_ap_ack or ap_reg_ioackin_g_itu_iface_req_V_ap_ack)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_g_itu_iface_req_V_ap_ack)) begin
        ap_sig_ioackin_g_itu_iface_req_V_ap_ack = g_itu_iface_req_V_ap_ack;
    end else begin
        ap_sig_ioackin_g_itu_iface_req_V_ap_ack = ap_const_logic_1;
    end
end

/// cfg_req_V_ap_ack assign process. ///
always @ (tmp_1_fu_140_p3 or ap_CS_fsm or tmp_2_fu_168_p2 or ap_sig_bdd_43 or ap_sig_ioackin_g_itu_iface_req_V_ap_ack)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))))) begin
        cfg_req_V_ap_ack = ap_const_logic_1;
    end else begin
        cfg_req_V_ap_ack = ap_const_logic_0;
    end
end

/// cfg_resp_V_ap_vld assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_77 or ap_reg_ioackin_cfg_resp_V_ap_ack)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~ap_sig_bdd_77 & (ap_const_logic_0 == ap_reg_ioackin_cfg_resp_V_ap_ack))) begin
        cfg_resp_V_ap_vld = ap_const_logic_1;
    end else begin
        cfg_resp_V_ap_vld = ap_const_logic_0;
    end
end

/// g_itu_iface_req_V assign process. ///
always @ (tmp_1_fu_140_p3 or tmp_1_reg_313 or ap_CS_fsm or tmp_2_fu_168_p2 or ap_sig_bdd_43 or ap_sig_ioackin_g_itu_iface_req_V_ap_ack or tmp_2_reg_320 or tmp_5_i_reg_342 or ap_sig_bdd_77 or ap_sig_ioackin_cfg_resp_V_ap_ack or r_V_fu_246_p1 or req_V_2_fu_278_p3 or req_V_1_fu_304_p3)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342)) | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack)))) begin
        g_itu_iface_req_V = req_V_1_fu_304_p3;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342)) | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack)))) begin
        g_itu_iface_req_V = req_V_2_fu_278_p3;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack))))) begin
        g_itu_iface_req_V = r_V_fu_246_p1;
    end else begin
        g_itu_iface_req_V = 'bx;
    end
end

/// g_itu_iface_req_V_ap_vld assign process. ///
always @ (tmp_1_fu_140_p3 or tmp_1_reg_313 or ap_CS_fsm or tmp_2_fu_168_p2 or ap_sig_bdd_43 or tmp_2_reg_320 or tmp_5_i_reg_342 or ap_sig_bdd_77 or ap_reg_ioackin_g_itu_iface_req_V_ap_ack)
begin
    if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & ~ap_sig_bdd_43 & (ap_const_logic_0 == ap_reg_ioackin_g_itu_iface_req_V_ap_ack)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342) & (ap_const_logic_0 == ap_reg_ioackin_g_itu_iface_req_V_ap_ack) & ~ap_sig_bdd_77) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342) & (ap_const_logic_0 == ap_reg_ioackin_g_itu_iface_req_V_ap_ack) & ~ap_sig_bdd_77))) begin
        g_itu_iface_req_V_ap_vld = ap_const_logic_1;
    end else begin
        g_itu_iface_req_V_ap_vld = ap_const_logic_0;
    end
end

/// g_itu_iface_resp_V_ap_ack assign process. ///
always @ (tmp_1_fu_140_p3 or tmp_1_reg_313 or ap_CS_fsm or tmp_2_fu_168_p2 or ap_sig_bdd_43 or ap_sig_ioackin_g_itu_iface_req_V_ap_ack or tmp_2_reg_320 or tmp_5_i_reg_342 or ap_sig_bdd_77 or ap_sig_ioackin_cfg_resp_V_ap_ack)
begin
    if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & ~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)))) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342)) | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack))) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342)) | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack))))) begin
        g_itu_iface_resp_V_ap_ack = ap_const_logic_1;
    end else begin
        g_itu_iface_resp_V_ap_ack = ap_const_logic_0;
    end
end

/// p_0173_1_phi_fu_127_p6 assign process. ///
always @ (tmp_1_reg_313 or ap_CS_fsm or tmp_2_reg_320 or p_0173_1_reg_122)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320))) begin
        p_0173_1_phi_fu_127_p6 = ap_const_lv33_1ABCDABCD;
    end else begin
        p_0173_1_phi_fu_127_p6 = p_0173_1_reg_122;
    end
end
always @ (tmp_1_fu_140_p3 or tmp_1_reg_313 or ap_CS_fsm or tmp_2_fu_168_p2 or ap_sig_bdd_43 or ap_sig_ioackin_g_itu_iface_req_V_ap_ack or tmp_2_reg_320 or tmp_5_i_reg_342 or ap_sig_bdd_77 or ap_sig_ioackin_cfg_resp_V_ap_ack)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_sig_bdd_43 | (~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342)) | ((ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack))) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_248 assign process. ///
always @ (cfg_resp_V_ap_ack or ap_sig_bdd_77)
begin
    ap_sig_bdd_248 = (~ap_sig_bdd_77 & (ap_const_logic_1 == cfg_resp_V_ap_ack));
end

/// ap_sig_bdd_43 assign process. ///
always @ (cfg_req_V_ap_vld or g_itu_iface_resp_V_ap_vld or tmp_1_fu_140_p3 or tmp_2_fu_168_p2)
begin
    ap_sig_bdd_43 = ((cfg_req_V_ap_vld == ap_const_logic_0) | ((g_itu_iface_resp_V_ap_vld == ap_const_logic_0) & ~(tmp_1_fu_140_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_168_p2)));
end

/// ap_sig_bdd_77 assign process. ///
always @ (g_itu_iface_resp_V_ap_vld or tmp_1_reg_313 or tmp_2_reg_320 or tmp_5_i_reg_342)
begin
    ap_sig_bdd_77 = (((g_itu_iface_resp_V_ap_vld == ap_const_logic_0) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & (ap_const_lv1_0 == tmp_5_i_reg_342)) | ((g_itu_iface_resp_V_ap_vld == ap_const_logic_0) & ~(tmp_1_reg_313 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_320) & ~(ap_const_lv1_0 == tmp_5_i_reg_342)));
end
assign cfg_resp_V = p_0173_1_phi_fu_127_p6;
assign r_V_fu_246_p1 = $unsigned(tmp_fu_234_p5);
assign raddr_V_fu_158_p4 = {{cfg_req_V[ap_const_lv32_44 : ap_const_lv32_40]}};
assign req_V_1_fu_304_p3 = {{ap_const_lv1_1}, {tmp_3_fu_300_p1}};
assign req_V_2_fu_278_p3 = {{ap_const_lv1_1}, {tmp_7_fu_274_p1}};
assign tmp_1_fu_140_p3 = cfg_req_V[ap_const_lv32_45];
assign tmp_2_fu_168_p2 = (raddr_V_fu_158_p4 == ap_const_lv5_0? 1'b1: 1'b0);
assign tmp_3_fu_300_p1 = $unsigned(tmp_5_fu_287_p7);
assign tmp_5_fu_287_p7 = {{{{{{s_last_ds_id_V_load_reg_324}, {ap_const_lv16_0}}, {s_last_index_V_load_reg_330}}, {ap_const_lv24_0}}, {tmp_8_reg_336}}, {ap_const_lv1_1}};
assign tmp_5_i_fu_255_p2 = (s_pred_V == ap_const_lv3_0? 1'b1: 1'b0);
assign tmp_6_fu_261_p7 = {{{{{{s_last_ds_id_V_load_reg_324}, {ap_const_lv16_0}}, {s_last_index_V_load_reg_330}}, {ap_const_lv24_0}}, {tmp_8_reg_336}}, {ap_const_lv1_0}};
assign tmp_7_fu_274_p1 = $unsigned(tmp_6_fu_261_p7);
assign tmp_8_fu_251_p1 = g_itu_iface_resp_V[6:0];
assign tmp_fu_234_p5 = {{{{s_first_ds_id_V}, {ap_const_lv16_0}}, {s_first_index_V}}, {ap_const_lv32_0}};
always @ (posedge ap_clk)
begin
    p_0173_1_reg_122[1] <= 1'b0;
    p_0173_1_reg_122[5:4] <= 2'b00;
    p_0173_1_reg_122[10:10] <= 1'b0;
    p_0173_1_reg_122[12:12] <= 1'b0;
    p_0173_1_reg_122[14:14] <= 1'b0;
    p_0173_1_reg_122[17:17] <= 1'b0;
    p_0173_1_reg_122[21:20] <= 2'b00;
    p_0173_1_reg_122[26:26] <= 1'b0;
    p_0173_1_reg_122[28:28] <= 1'b0;
    p_0173_1_reg_122[30] <= 1'b0;
end



endmodule //top

