// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top,hls_ip_2014_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.907250,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}" *)

 /* verilator lint_off WIDTH */
module FindIfUnitVRTL (
        clk,
        reset,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cfg_req_V,
        cfg_req_V_ap_vld,
        cfg_req_V_ap_ack,
        cfg_resp_V,
        cfg_resp_V_ap_vld,
        cfg_resp_V_ap_ack,
        g_itu_iface_resp_V,
        g_itu_iface_resp_V_ap_vld,
        g_itu_iface_resp_V_ap_ack,
        g_itu_iface_req_V,
        g_itu_iface_req_V_ap_vld,
        g_itu_iface_req_V_ap_ack
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 1'b0;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv33_100000000 = 33'b100000000000000000000000000000000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv33_0 = 33'b000000000000000000000000000000000;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv5_2 = 5'b10;
parameter    ap_const_lv32_45 = 32'b1000101;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_40 = 32'b1000000;
parameter    ap_const_lv32_44 = 32'b1000100;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv24_0 = 24'b000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_true = 1'b1;

input   clk;
input   reset;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [69:0] cfg_req_V;
input   cfg_req_V_ap_vld;
output   cfg_req_V_ap_ack;
output  [32:0] cfg_resp_V;
output   cfg_resp_V_ap_vld;
input   cfg_resp_V_ap_ack;
input  [32:0] g_itu_iface_resp_V;
input   g_itu_iface_resp_V_ap_vld;
output   g_itu_iface_resp_V_ap_ack;
output  [96:0] g_itu_iface_req_V;
output   g_itu_iface_req_V_ap_vld;
input   g_itu_iface_req_V_ap_ack;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg cfg_req_V_ap_ack;
reg cfg_resp_V_ap_vld;
reg g_itu_iface_resp_V_ap_ack;
reg g_itu_iface_req_V_ap_vld;
reg   [0:0] ap_CS_fsm = 1'b0;
reg   [15:0] s_first_ds_id_V = 16'b0000000000000000;
reg   [15:0] s_first_index_V = 16'b0000000000000000;
reg   [32:0] p_090_1_phi_fu_99_p4;
wire   [0:0] tmp_fu_109_p3;
wire   [0:0] tmp_2_fu_137_p2;
reg    ap_sig_bdd_49;
reg    ap_sig_ioackin_g_itu_iface_req_V_ap_ack;
reg    ap_sig_ioackin_cfg_resp_V_ap_ack;
wire   [4:0] raddr_V_fu_127_p4;
reg    ap_reg_ioackin_g_itu_iface_req_V_ap_ack = 1'b0;
reg    ap_reg_ioackin_cfg_resp_V_ap_ack = 1'b0;
wire   [6:0] tmp_4_fu_151_p1;
wire   [79:0] tmp_3_fu_155_p7;
wire   [95:0] tmp_1_fu_171_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_sig_bdd_148;
reg    ap_sig_bdd_150;
reg    ap_sig_bdd_73;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge clk)
begin : ap_ret_ap_CS_fsm
    if (reset == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_cfg_resp_V_ap_ack assign process. ///
always @ (posedge clk)
begin : ap_ret_ap_reg_ioackin_cfg_resp_V_ap_ack
    if (reset == 1'b1) begin
        ap_reg_ioackin_cfg_resp_V_ap_ack <= ap_const_logic_0;
    end else begin
        if ((ap_ST_st1_fsm_0 == ap_CS_fsm)) begin
            if (~(ap_sig_bdd_49 | (~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack))) begin
                ap_reg_ioackin_cfg_resp_V_ap_ack <= ap_const_logic_0;
            end else if (ap_sig_bdd_148) begin
                ap_reg_ioackin_cfg_resp_V_ap_ack <= ap_const_logic_1;
            end
        end
    end
end

/// ap_reg_ioackin_g_itu_iface_req_V_ap_ack assign process. ///
always @ (posedge clk)
begin : ap_ret_ap_reg_ioackin_g_itu_iface_req_V_ap_ack
    if (reset == 1'b1) begin
        ap_reg_ioackin_g_itu_iface_req_V_ap_ack <= ap_const_logic_0;
    end else begin
        if (ap_sig_bdd_73) begin
            if (~(ap_sig_bdd_49 | (~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack))) begin
                ap_reg_ioackin_g_itu_iface_req_V_ap_ack <= ap_const_logic_0;
            end else if (ap_sig_bdd_150) begin
                ap_reg_ioackin_g_itu_iface_req_V_ap_ack <= ap_const_logic_1;
            end
        end
    end
end

/// assign process. ///
always @(posedge clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_sig_bdd_49 | (~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack)) & (raddr_V_fu_127_p4 == ap_const_lv5_1))) begin
        s_first_ds_id_V <= {{cfg_req_V[ap_const_lv32_2F : ap_const_lv32_20]}};
    end
end

/// assign process. ///
always @(posedge clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_sig_bdd_49 | (~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack)) & (raddr_V_fu_127_p4 == ap_const_lv5_2))) begin
        s_first_index_V <= {{cfg_req_V[ap_const_lv32_2F : ap_const_lv32_20]}};
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or tmp_fu_109_p3 or tmp_2_fu_137_p2 or ap_sig_bdd_49 or ap_sig_ioackin_g_itu_iface_req_V_ap_ack or ap_sig_ioackin_cfg_resp_V_ap_ack)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_sig_bdd_49 | (~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or tmp_fu_109_p3 or tmp_2_fu_137_p2 or ap_sig_bdd_49 or ap_sig_ioackin_g_itu_iface_req_V_ap_ack or ap_sig_ioackin_cfg_resp_V_ap_ack)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_sig_bdd_49 | (~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack)))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_ioackin_cfg_resp_V_ap_ack assign process. ///
always @ (cfg_resp_V_ap_ack or ap_reg_ioackin_cfg_resp_V_ap_ack)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_cfg_resp_V_ap_ack)) begin
        ap_sig_ioackin_cfg_resp_V_ap_ack = cfg_resp_V_ap_ack;
    end else begin
        ap_sig_ioackin_cfg_resp_V_ap_ack = ap_const_logic_1;
    end
end

/// ap_sig_ioackin_g_itu_iface_req_V_ap_ack assign process. ///
always @ (g_itu_iface_req_V_ap_ack or ap_reg_ioackin_g_itu_iface_req_V_ap_ack)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_g_itu_iface_req_V_ap_ack)) begin
        ap_sig_ioackin_g_itu_iface_req_V_ap_ack = g_itu_iface_req_V_ap_ack;
    end else begin
        ap_sig_ioackin_g_itu_iface_req_V_ap_ack = ap_const_logic_1;
    end
end

/// cfg_req_V_ap_ack assign process. ///
always @ (ap_CS_fsm or tmp_fu_109_p3 or tmp_2_fu_137_p2 or ap_sig_bdd_49 or ap_sig_ioackin_g_itu_iface_req_V_ap_ack or ap_sig_ioackin_cfg_resp_V_ap_ack)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_sig_bdd_49 | (~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack)))) begin
        cfg_req_V_ap_ack = ap_const_logic_1;
    end else begin
        cfg_req_V_ap_ack = ap_const_logic_0;
    end
end

/// cfg_resp_V_ap_vld assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_49 or ap_reg_ioackin_cfg_resp_V_ap_ack)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_49 & (ap_const_logic_0 == ap_reg_ioackin_cfg_resp_V_ap_ack))) begin
        cfg_resp_V_ap_vld = ap_const_logic_1;
    end else begin
        cfg_resp_V_ap_vld = ap_const_logic_0;
    end
end

/// g_itu_iface_req_V_ap_vld assign process. ///
always @ (ap_CS_fsm or tmp_fu_109_p3 or tmp_2_fu_137_p2 or ap_sig_bdd_49 or ap_reg_ioackin_g_itu_iface_req_V_ap_ack)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2) & ~ap_sig_bdd_49 & (ap_const_logic_0 == ap_reg_ioackin_g_itu_iface_req_V_ap_ack))) begin
        g_itu_iface_req_V_ap_vld = ap_const_logic_1;
    end else begin
        g_itu_iface_req_V_ap_vld = ap_const_logic_0;
    end
end

/// g_itu_iface_resp_V_ap_ack assign process. ///
always @ (ap_CS_fsm or tmp_fu_109_p3 or tmp_2_fu_137_p2 or ap_sig_bdd_49 or ap_sig_ioackin_g_itu_iface_req_V_ap_ack or ap_sig_ioackin_cfg_resp_V_ap_ack)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2) & ~(ap_sig_bdd_49 | (~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2) & (ap_const_logic_0 == ap_sig_ioackin_g_itu_iface_req_V_ap_ack)) | (ap_const_logic_0 == ap_sig_ioackin_cfg_resp_V_ap_ack)))) begin
        g_itu_iface_resp_V_ap_ack = ap_const_logic_1;
    end else begin
        g_itu_iface_resp_V_ap_ack = ap_const_logic_0;
    end
end

/// p_090_1_phi_fu_99_p4 assign process. ///
always @ (ap_CS_fsm or tmp_fu_109_p3)
begin
    if ((ap_ST_st1_fsm_0 == ap_CS_fsm)) begin
        if ((tmp_fu_109_p3 == ap_const_lv1_0)) begin
            p_090_1_phi_fu_99_p4 = ap_const_lv33_0;
        end else if (~(tmp_fu_109_p3 == ap_const_lv1_0)) begin
            p_090_1_phi_fu_99_p4 = ap_const_lv33_100000000;
        end else begin
            p_090_1_phi_fu_99_p4 = 'bx;
        end
    end else begin
        p_090_1_phi_fu_99_p4 = 'bx;
    end
end
always @ (ap_CS_fsm or tmp_fu_109_p3 or tmp_2_fu_137_p2 or ap_sig_bdd_49 or ap_sig_ioackin_g_itu_iface_req_V_ap_ack or ap_sig_ioackin_cfg_resp_V_ap_ack)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_148 assign process. ///
always @ (cfg_resp_V_ap_ack or ap_sig_bdd_49)
begin
    ap_sig_bdd_148 = (~ap_sig_bdd_49 & (ap_const_logic_1 == cfg_resp_V_ap_ack));
end

/// ap_sig_bdd_150 assign process. ///
always @ (g_itu_iface_req_V_ap_ack or ap_sig_bdd_49)
begin
    ap_sig_bdd_150 = ((ap_const_logic_1 == g_itu_iface_req_V_ap_ack) & ~ap_sig_bdd_49);
end

/// ap_sig_bdd_49 assign process. ///
always @ (ap_start or cfg_req_V_ap_vld or g_itu_iface_resp_V_ap_vld or tmp_fu_109_p3 or tmp_2_fu_137_p2)
begin
    ap_sig_bdd_49 = ((cfg_req_V_ap_vld == ap_const_logic_0) | ((g_itu_iface_resp_V_ap_vld == ap_const_logic_0) & ~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2)) | (ap_start == ap_const_logic_0));
end

/// ap_sig_bdd_73 assign process. ///
always @ (ap_CS_fsm or tmp_fu_109_p3 or tmp_2_fu_137_p2)
begin
    ap_sig_bdd_73 = ((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(tmp_fu_109_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_137_p2));
end
assign cfg_resp_V = p_090_1_phi_fu_99_p4;
assign g_itu_iface_req_V = {{ap_const_lv1_1}, {tmp_1_fu_171_p1}};
assign raddr_V_fu_127_p4 = {{cfg_req_V[ap_const_lv32_44 : ap_const_lv32_40]}};
assign tmp_1_fu_171_p1 = $unsigned(tmp_3_fu_155_p7);
assign tmp_2_fu_137_p2 = (raddr_V_fu_127_p4 == ap_const_lv5_0? 1'b1: 1'b0);
assign tmp_3_fu_155_p7 = {{{{{{s_first_ds_id_V}, {ap_const_lv16_0}}, {s_first_index_V}}, {ap_const_lv24_0}}, {tmp_4_fu_151_p1}}, {ap_const_lv1_1}};
assign tmp_4_fu_151_p1 = g_itu_iface_resp_V[6:0];
assign tmp_fu_109_p3 = cfg_req_V[ap_const_lv32_45];


endmodule //top

/* lint_on */
