// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
//
// ===========================================================

`timescale 1 ns / 1 ps

(* CORE_GENERATION_INFO="VecincrXcelHLS,hls_ip_2014_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.518000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}" *)

/* verilator lint_off WIDTH */
module VecincrXcelHLS (
        ap_clk,
        ap_rst,
        xcelreq_V,
        xcelreq_V_ap_vld,
        xcelreq_V_ap_ack,
        xcelresp_V,
        xcelresp_V_ap_vld,
        xcelresp_V_ap_ack,
        memreq_V,
        memreq_V_ap_vld,
        memreq_V_ap_ack,
        memresp_V,
        memresp_V_ap_vld,
        memresp_V_ap_ack
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b000;
parameter    ap_ST_st2_fsm_1 = 3'b1;
parameter    ap_ST_st3_fsm_2 = 3'b10;
parameter    ap_ST_st4_fsm_3 = 3'b11;
parameter    ap_ST_pp0_stg0_fsm_4 = 3'b100;
parameter    ap_ST_pp0_stg1_fsm_5 = 3'b101;
parameter    ap_ST_st8_fsm_6 = 3'b110;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_2A = 32'b101010;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_38 = 32'b111000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv34_0 = 34'b0000000000000000000000000000000000;
parameter    ap_const_lv11_100 = 11'b100000000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input  [56:0] xcelreq_V;
input   xcelreq_V_ap_vld;
output   xcelreq_V_ap_ack;
output  [51:0] xcelresp_V;
output   xcelresp_V_ap_vld;
input   xcelresp_V_ap_ack;
output  [76:0] memreq_V;
output   memreq_V_ap_vld;
input   memreq_V_ap_ack;
input  [44:0] memresp_V;
input   memresp_V_ap_vld;
output   memresp_V_ap_ack;

reg xcelreq_V_ap_ack;
reg[51:0] xcelresp_V;
reg xcelresp_V_ap_vld;
reg[76:0] memreq_V;
reg memreq_V_ap_vld;
reg memresp_V_ap_ack;
reg   [31:0] i_0_i_reg_133;
reg   [31:0] base_V_reg_325;
reg   [2:0] ap_CS_fsm = 3'b000;
reg    ap_sig_ioackin_xcelresp_V_ap_ack;
reg   [31:0] size_V_reg_330;
reg   [31:0] incr_V_reg_335;
wire   [0:0] exitcond_fu_241_p2;
reg   [0:0] exitcond_reg_340;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_ioackin_memreq_V_ap_ack;
reg    ap_sig_bdd_59;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
wire   [31:0] i_fu_246_p2;
reg   [31:0] i_reg_344;
wire   [31:0] tmp_addr_V_fu_258_p2;
reg   [31:0] tmp_addr_V_reg_349;
reg   [31:0] i_0_i_phi_fu_137_p4;
wire   [51:0] tmp_1_fu_173_p4;
wire   [51:0] tmp_3_fu_191_p4;
wire   [51:0] tmp_5_fu_209_p4;
wire   [51:0] tmp_7189_fu_227_p4;
wire   [51:0] tmp_13_fu_311_p4;
reg    ap_reg_ioackin_xcelresp_V_ap_ack = 1'b0;
wire   [76:0] tmp_8199_fu_263_p4;
wire   [76:0] tmp_10_1_fu_291_p5;
reg    ap_reg_ioackin_memreq_V_ap_ack = 1'b0;
wire   [8:0] grp_fu_159_p4;
wire   [10:0] tmp_id_V_fu_169_p1;
wire   [10:0] tmp_id_V_1_fu_187_p1;
wire   [10:0] tmp_id_V_2_fu_205_p1;
wire   [10:0] tmp_id_V_3_fu_223_p1;
wire   [31:0] tmp_14_fu_252_p2;
wire   [31:0] tmp_15_fu_282_p1;
wire   [31:0] temp_V_fu_286_p2;
wire   [10:0] tmp_id_V_4_fu_307_p1;
reg   [2:0] ap_NS_fsm;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_memreq_V_ap_ack assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_memreq_V_ap_ack
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_memreq_V_ap_ack <= ap_const_logic_0;
    end else begin
        if ((((ap_ST_pp0_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & ~(((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack)) | (ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_reg_340 == ap_const_lv1_0) & (ap_ST_pp0_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_sig_bdd_59 | ((ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack) & (exitcond_reg_340 == ap_const_lv1_0))))))) begin
            ap_reg_ioackin_memreq_V_ap_ack <= ap_const_logic_0;
        end else if ((((ap_ST_pp0_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_1 == memreq_V_ap_ack) & ~(ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_reg_340 == ap_const_lv1_0) & (ap_ST_pp0_stg1_fsm_5 == ap_CS_fsm) & (ap_const_logic_1 == memreq_V_ap_ack) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_59)))) begin
            ap_reg_ioackin_memreq_V_ap_ack <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ioackin_xcelresp_V_ap_ack assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_xcelresp_V_ap_ack
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_xcelresp_V_ap_ack <= ap_const_logic_0;
    end else begin
        if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st2_fsm_1 == ap_CS_fsm)) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st3_fsm_2 == ap_CS_fsm)) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st4_fsm_3 == ap_CS_fsm)) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st8_fsm_6 == ap_CS_fsm)))) begin
            ap_reg_ioackin_xcelresp_V_ap_ack <= ap_const_logic_0;
        end else if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == xcelresp_V_ap_ack) & ~(xcelreq_V_ap_vld == ap_const_logic_0)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_logic_1 == xcelresp_V_ap_ack) & ~(xcelreq_V_ap_vld == ap_const_logic_0)) | ((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == xcelresp_V_ap_ack) & ~(xcelreq_V_ap_vld == ap_const_logic_0)) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == xcelresp_V_ap_ack) & ~(xcelreq_V_ap_vld == ap_const_logic_0)) | ((ap_ST_st8_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == xcelresp_V_ap_ack) & ~(xcelreq_V_ap_vld == ap_const_logic_0)))) begin
            ap_reg_ioackin_xcelresp_V_ap_ack <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_4 == ap_CS_fsm) & ~(((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack)) | (ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(exitcond_fu_241_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st4_fsm_3 == ap_CS_fsm))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((exitcond_reg_340 == ap_const_lv1_0) & (ap_ST_pp0_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_sig_bdd_59 | ((ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack) & (exitcond_reg_340 == ap_const_lv1_0)))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if (((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st4_fsm_3 == ap_CS_fsm)) | ((ap_ST_pp0_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_sig_bdd_59 | ((ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack) & (exitcond_reg_340 == ap_const_lv1_0)))) & ~(exitcond_reg_340 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_4 == ap_CS_fsm) & (exitcond_reg_340 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack)) | (ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        i_0_i_reg_133 <= i_reg_344;
    end else if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st4_fsm_3 == ap_CS_fsm))) begin
        i_0_i_reg_133 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)))) begin
        base_V_reg_325 <= {{xcelreq_V[ap_const_lv32_2A : ap_const_lv32_B]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack)) | (ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        exitcond_reg_340 <= exitcond_fu_241_p2;
        i_reg_344 <= i_fu_246_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        incr_V_reg_335 <= {{xcelreq_V[ap_const_lv32_2A : ap_const_lv32_B]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st2_fsm_1 == ap_CS_fsm))) begin
        size_V_reg_330 <= {{xcelreq_V[ap_const_lv32_2A : ap_const_lv32_B]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & ~(((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack)) | (ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        tmp_addr_V_reg_349 <= tmp_addr_V_fu_258_p2;
    end
end

/// ap_sig_ioackin_memreq_V_ap_ack assign process. ///
always @ (memreq_V_ap_ack or ap_reg_ioackin_memreq_V_ap_ack)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_memreq_V_ap_ack)) begin
        ap_sig_ioackin_memreq_V_ap_ack = memreq_V_ap_ack;
    end else begin
        ap_sig_ioackin_memreq_V_ap_ack = ap_const_logic_1;
    end
end

/// ap_sig_ioackin_xcelresp_V_ap_ack assign process. ///
always @ (xcelresp_V_ap_ack or ap_reg_ioackin_xcelresp_V_ap_ack)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)) begin
        ap_sig_ioackin_xcelresp_V_ap_ack = xcelresp_V_ap_ack;
    end else begin
        ap_sig_ioackin_xcelresp_V_ap_ack = ap_const_logic_1;
    end
end

/// i_0_i_phi_fu_137_p4 assign process. ///
always @ (i_0_i_reg_133 or ap_CS_fsm or exitcond_reg_340 or ap_reg_ppiten_pp0_it1 or i_reg_344)
begin
    if (((ap_ST_pp0_stg0_fsm_4 == ap_CS_fsm) & (exitcond_reg_340 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        i_0_i_phi_fu_137_p4 = i_reg_344;
    end else begin
        i_0_i_phi_fu_137_p4 = i_0_i_reg_133;
    end
end

/// memreq_V assign process. ///
always @ (ap_CS_fsm or exitcond_fu_241_p2 or exitcond_reg_340 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_memreq_V_ap_ack or ap_sig_bdd_59 or ap_reg_ppiten_pp0_it1 or tmp_8199_fu_263_p4 or tmp_10_1_fu_291_p5)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_reg_340 == ap_const_lv1_0) & (ap_ST_pp0_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_sig_bdd_59 | ((ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack) & (exitcond_reg_340 == ap_const_lv1_0)))))) begin
        memreq_V = tmp_10_1_fu_291_p5;
    end else if (((ap_ST_pp0_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & ~(((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack)) | (ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))))) begin
        memreq_V = tmp_8199_fu_263_p4;
    end else begin
        memreq_V = 'bx;
    end
end

/// memreq_V_ap_vld assign process. ///
always @ (ap_CS_fsm or exitcond_fu_241_p2 or exitcond_reg_340 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_59 or ap_reg_ppiten_pp0_it1 or ap_reg_ioackin_memreq_V_ap_ack)
begin
    if ((((ap_ST_pp0_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & ~(ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_logic_0 == ap_reg_ioackin_memreq_V_ap_ack)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_reg_340 == ap_const_lv1_0) & (ap_ST_pp0_stg1_fsm_5 == ap_CS_fsm) & (ap_const_logic_0 == ap_reg_ioackin_memreq_V_ap_ack) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_59)))) begin
        memreq_V_ap_vld = ap_const_logic_1;
    end else begin
        memreq_V_ap_vld = ap_const_logic_0;
    end
end

/// memresp_V_ap_ack assign process. ///
always @ (ap_CS_fsm or exitcond_fu_241_p2 or exitcond_reg_340 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_memreq_V_ap_ack or ap_sig_bdd_59 or ap_reg_ppiten_pp0_it1)
begin
    if ((((ap_ST_pp0_stg0_fsm_4 == ap_CS_fsm) & (exitcond_reg_340 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack)) | (ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_reg_340 == ap_const_lv1_0) & (ap_ST_pp0_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_sig_bdd_59 | ((ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack) & (exitcond_reg_340 == ap_const_lv1_0))))))) begin
        memresp_V_ap_ack = ap_const_logic_1;
    end else begin
        memresp_V_ap_ack = ap_const_logic_0;
    end
end

/// xcelreq_V_ap_ack assign process. ///
always @ (xcelreq_V_ap_vld or ap_CS_fsm or ap_sig_ioackin_xcelresp_V_ap_ack)
begin
    if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st2_fsm_1 == ap_CS_fsm)) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st3_fsm_2 == ap_CS_fsm)) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st4_fsm_3 == ap_CS_fsm)) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st8_fsm_6 == ap_CS_fsm)))) begin
        xcelreq_V_ap_ack = ap_const_logic_1;
    end else begin
        xcelreq_V_ap_ack = ap_const_logic_0;
    end
end

/// xcelresp_V assign process. ///
always @ (xcelreq_V_ap_vld or ap_CS_fsm or ap_sig_ioackin_xcelresp_V_ap_ack or tmp_1_fu_173_p4 or tmp_3_fu_191_p4 or tmp_5_fu_209_p4 or tmp_7189_fu_227_p4 or tmp_13_fu_311_p4)
begin
    if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st8_fsm_6 == ap_CS_fsm))) begin
        xcelresp_V = tmp_13_fu_311_p4;
    end else if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st4_fsm_3 == ap_CS_fsm))) begin
        xcelresp_V = tmp_7189_fu_227_p4;
    end else if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        xcelresp_V = tmp_5_fu_209_p4;
    end else if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st2_fsm_1 == ap_CS_fsm))) begin
        xcelresp_V = tmp_3_fu_191_p4;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)))) begin
        xcelresp_V = tmp_1_fu_173_p4;
    end else begin
        xcelresp_V = 'bx;
    end
end

/// xcelresp_V_ap_vld assign process. ///
always @ (xcelreq_V_ap_vld or ap_CS_fsm or ap_reg_ioackin_xcelresp_V_ap_ack)
begin
    if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(xcelreq_V_ap_vld == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(xcelreq_V_ap_vld == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)) | ((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(xcelreq_V_ap_vld == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(xcelreq_V_ap_vld == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)) | ((ap_ST_st8_fsm_6 == ap_CS_fsm) & ~(xcelreq_V_ap_vld == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)))) begin
        xcelresp_V_ap_vld = ap_const_logic_1;
    end else begin
        xcelresp_V_ap_vld = ap_const_logic_0;
    end
end
always @ (xcelreq_V_ap_vld or ap_CS_fsm or ap_sig_ioackin_xcelresp_V_ap_ack or exitcond_fu_241_p2 or exitcond_reg_340 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_memreq_V_ap_ack or ap_sig_bdd_59 or ap_reg_ppiten_pp0_it1)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 :
            if (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 :
            if (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        ap_ST_st3_fsm_2 :
            if (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st4_fsm_3 :
            if (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        ap_ST_pp0_stg0_fsm_4 :
            if ((~(((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack)) | (ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack)) | (ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(exitcond_fu_241_p2 == ap_const_lv1_0)))) begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_5;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_fu_241_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack)) | (ap_sig_bdd_59 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) & ~(exitcond_fu_241_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st8_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_4;
            end
        ap_ST_pp0_stg1_fsm_5 :
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_sig_bdd_59 | ((ap_const_logic_0 == ap_sig_ioackin_memreq_V_ap_ack) & (exitcond_reg_340 == ap_const_lv1_0))))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_5;
            end
        ap_ST_st8_fsm_6 :
            if (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_6;
            end
        default :
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_59 assign process. ///
always @ (memresp_V_ap_vld or exitcond_reg_340)
begin
    ap_sig_bdd_59 = ((memresp_V_ap_vld == ap_const_logic_0) & (exitcond_reg_340 == ap_const_lv1_0));
end
assign exitcond_fu_241_p2 = (i_0_i_phi_fu_137_p4 == size_V_reg_330? 1'b1: 1'b0);
assign grp_fu_159_p4 = {{xcelreq_V[ap_const_lv32_38 : ap_const_lv32_30]}};
assign i_fu_246_p2 = (i_0_i_phi_fu_137_p4 + ap_const_lv32_1);
assign temp_V_fu_286_p2 = (incr_V_reg_335 + tmp_15_fu_282_p1);
assign tmp_10_1_fu_291_p5 = {{{{ap_const_lv11_100}, {tmp_addr_V_reg_349}}, {ap_const_lv2_0}}, {temp_V_fu_286_p2}};
assign tmp_13_fu_311_p4 = {{{grp_fu_159_p4}, {ap_const_lv32_1}}, {tmp_id_V_4_fu_307_p1}};
assign tmp_14_fu_252_p2 = i_0_i_phi_fu_137_p4 << ap_const_lv32_2;
assign tmp_15_fu_282_p1 = memresp_V[31:0];
assign tmp_1_fu_173_p4 = {{{grp_fu_159_p4}, {ap_const_lv32_0}}, {tmp_id_V_fu_169_p1}};
assign tmp_3_fu_191_p4 = {{{grp_fu_159_p4}, {ap_const_lv32_0}}, {tmp_id_V_1_fu_187_p1}};
assign tmp_5_fu_209_p4 = {{{grp_fu_159_p4}, {ap_const_lv32_0}}, {tmp_id_V_2_fu_205_p1}};
assign tmp_7189_fu_227_p4 = {{{grp_fu_159_p4}, {ap_const_lv32_0}}, {tmp_id_V_3_fu_223_p1}};
assign tmp_8199_fu_263_p4 = {{{ap_const_lv11_0}, {tmp_addr_V_fu_258_p2}}, {ap_const_lv34_0}};
assign tmp_addr_V_fu_258_p2 = (base_V_reg_325 + tmp_14_fu_252_p2);
assign tmp_id_V_1_fu_187_p1 = xcelreq_V[10:0];
assign tmp_id_V_2_fu_205_p1 = xcelreq_V[10:0];
assign tmp_id_V_3_fu_223_p1 = xcelreq_V[10:0];
assign tmp_id_V_4_fu_307_p1 = xcelreq_V[10:0];
assign tmp_id_V_fu_169_p1 = xcelreq_V[10:0];


endmodule //VecincrXcelHLS

