// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
//
// ===========================================================

`timescale 1 ns / 1 ps

(* CORE_GENERATION_INFO="GcdXcelHLS,hls_ip_2014_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.888000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}" *)

/* verilator lint_off WIDTH */
module GcdXcelHLS (
        ap_clk,
        ap_rst,
        xcelreq_V,
        xcelreq_V_ap_vld,
        xcelreq_V_ap_ack,
        xcelresp_V,
        xcelresp_V_ap_vld,
        xcelresp_V_ap_ack
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b000;
parameter    ap_ST_st2_fsm_1 = 3'b1;
parameter    ap_ST_st3_fsm_2 = 3'b10;
parameter    ap_ST_st4_fsm_3 = 3'b11;
parameter    ap_ST_st5_fsm_4 = 3'b100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_2A = 32'b101010;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_38 = 32'b111000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input  [56:0] xcelreq_V;
input   xcelreq_V_ap_vld;
output   xcelreq_V_ap_ack;
output  [51:0] xcelresp_V;
output   xcelresp_V_ap_vld;
input   xcelresp_V_ap_ack;

reg xcelreq_V_ap_ack;
reg[51:0] xcelresp_V;
reg xcelresp_V_ap_vld;
reg   [31:0] opA_V_reg_234;
reg   [2:0] ap_CS_fsm = 3'b000;
reg    ap_sig_ioackin_xcelresp_V_ap_ack;
reg   [31:0] opB_V_reg_239;
wire   [31:0] opA_V_assign_2_fu_200_p3;
wire   [0:0] tmp_5_fu_176_p2;
wire   [31:0] opB_V_assign_2_fu_208_p3;
reg   [31:0] tmp_data_V_reg_78;
reg   [31:0] opB_assign_reg_88;
wire   [51:0] tmp_1_fu_126_p4;
wire   [51:0] tmp_3_fu_144_p4;
wire   [51:0] tmp_595_fu_162_p4;
wire   [51:0] tmp_7_2_fu_220_p4;
reg    ap_reg_ioackin_xcelresp_V_ap_ack = 1'b0;
wire   [8:0] grp_fu_112_p4;
wire   [10:0] tmp_id_V_fu_122_p1;
wire   [10:0] tmp_id_V_1_fu_140_p1;
wire   [10:0] tmp_id_V_2_fu_158_p1;
wire   [0:0] tmp_8_fu_182_p2;
wire   [31:0] opA_V_assign_1_fu_188_p2;
wire   [31:0] opB_V_assign_1_fu_194_p2;
wire   [10:0] tmp_id_V_3_fu_216_p1;
reg   [2:0] ap_NS_fsm;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_xcelresp_V_ap_ack assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_xcelresp_V_ap_ack
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_xcelresp_V_ap_ack <= ap_const_logic_0;
    end else begin
        if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st2_fsm_1 == ap_CS_fsm)) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st3_fsm_2 == ap_CS_fsm)) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st5_fsm_4 == ap_CS_fsm)))) begin
            ap_reg_ioackin_xcelresp_V_ap_ack <= ap_const_logic_0;
        end else if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == xcelresp_V_ap_ack) & ~(xcelreq_V_ap_vld == ap_const_logic_0)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_logic_1 == xcelresp_V_ap_ack) & ~(xcelreq_V_ap_vld == ap_const_logic_0)) | ((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == xcelresp_V_ap_ack) & ~(xcelreq_V_ap_vld == ap_const_logic_0)) | ((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == xcelresp_V_ap_ack) & ~(xcelreq_V_ap_vld == ap_const_logic_0)))) begin
            ap_reg_ioackin_xcelresp_V_ap_ack <= ap_const_logic_1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & (tmp_5_fu_176_p2 == ap_const_lv1_0))) begin
        opB_assign_reg_88 <= opB_V_assign_2_fu_208_p3;
    end else if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        opB_assign_reg_88 <= opB_V_reg_239;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & (tmp_5_fu_176_p2 == ap_const_lv1_0))) begin
        tmp_data_V_reg_78 <= opA_V_assign_2_fu_200_p3;
    end else if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        tmp_data_V_reg_78 <= opA_V_reg_234;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)))) begin
        opA_V_reg_234 <= {{xcelreq_V[ap_const_lv32_2A : ap_const_lv32_B]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st2_fsm_1 == ap_CS_fsm))) begin
        opB_V_reg_239 <= {{xcelreq_V[ap_const_lv32_2A : ap_const_lv32_B]}};
    end
end

/// ap_sig_ioackin_xcelresp_V_ap_ack assign process. ///
always @ (xcelresp_V_ap_ack or ap_reg_ioackin_xcelresp_V_ap_ack)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)) begin
        ap_sig_ioackin_xcelresp_V_ap_ack = xcelresp_V_ap_ack;
    end else begin
        ap_sig_ioackin_xcelresp_V_ap_ack = ap_const_logic_1;
    end
end

/// xcelreq_V_ap_ack assign process. ///
always @ (xcelreq_V_ap_vld or ap_CS_fsm or ap_sig_ioackin_xcelresp_V_ap_ack)
begin
    if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st2_fsm_1 == ap_CS_fsm)) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st3_fsm_2 == ap_CS_fsm)) | (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st5_fsm_4 == ap_CS_fsm)))) begin
        xcelreq_V_ap_ack = ap_const_logic_1;
    end else begin
        xcelreq_V_ap_ack = ap_const_logic_0;
    end
end

/// xcelresp_V assign process. ///
always @ (xcelreq_V_ap_vld or ap_CS_fsm or ap_sig_ioackin_xcelresp_V_ap_ack or tmp_1_fu_126_p4 or tmp_3_fu_144_p4 or tmp_595_fu_162_p4 or tmp_7_2_fu_220_p4)
begin
    if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st5_fsm_4 == ap_CS_fsm))) begin
        xcelresp_V = tmp_7_2_fu_220_p4;
    end else if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        xcelresp_V = tmp_595_fu_162_p4;
    end else if ((~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)) & (ap_ST_st2_fsm_1 == ap_CS_fsm))) begin
        xcelresp_V = tmp_3_fu_144_p4;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack)))) begin
        xcelresp_V = tmp_1_fu_126_p4;
    end else begin
        xcelresp_V = 'bx;
    end
end

/// xcelresp_V_ap_vld assign process. ///
always @ (xcelreq_V_ap_vld or ap_CS_fsm or ap_reg_ioackin_xcelresp_V_ap_ack)
begin
    if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(xcelreq_V_ap_vld == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(xcelreq_V_ap_vld == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)) | ((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(xcelreq_V_ap_vld == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)) | ((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(xcelreq_V_ap_vld == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_xcelresp_V_ap_ack)))) begin
        xcelresp_V_ap_vld = ap_const_logic_1;
    end else begin
        xcelresp_V_ap_vld = ap_const_logic_0;
    end
end
always @ (xcelreq_V_ap_vld or ap_CS_fsm or ap_sig_ioackin_xcelresp_V_ap_ack or tmp_5_fu_176_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 :
            if (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 :
            if (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        ap_ST_st3_fsm_2 :
            if (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st4_fsm_3 :
            if ((tmp_5_fu_176_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        ap_ST_st5_fsm_4 :
            if (~((xcelreq_V_ap_vld == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_xcelresp_V_ap_ack))) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        default :
            ap_NS_fsm = 'bx;
    endcase
end
assign grp_fu_112_p4 = {{xcelreq_V[ap_const_lv32_38 : ap_const_lv32_30]}};
assign opA_V_assign_1_fu_188_p2 = (tmp_data_V_reg_78 - opB_assign_reg_88);
assign opA_V_assign_2_fu_200_p3 = ((tmp_8_fu_182_p2)? opA_V_assign_1_fu_188_p2: tmp_data_V_reg_78);
assign opB_V_assign_1_fu_194_p2 = (opB_assign_reg_88 - tmp_data_V_reg_78);
assign opB_V_assign_2_fu_208_p3 = ((tmp_8_fu_182_p2)? opB_assign_reg_88: opB_V_assign_1_fu_194_p2);
assign tmp_1_fu_126_p4 = {{{grp_fu_112_p4}, {ap_const_lv32_0}}, {tmp_id_V_fu_122_p1}};
assign tmp_3_fu_144_p4 = {{{grp_fu_112_p4}, {ap_const_lv32_0}}, {tmp_id_V_1_fu_140_p1}};
assign tmp_595_fu_162_p4 = {{{grp_fu_112_p4}, {ap_const_lv32_0}}, {tmp_id_V_2_fu_158_p1}};
assign tmp_5_fu_176_p2 = (tmp_data_V_reg_78 == opB_assign_reg_88? 1'b1: 1'b0);
assign tmp_7_2_fu_220_p4 = {{{grp_fu_112_p4}, {tmp_data_V_reg_78}}, {tmp_id_V_3_fu_216_p1}};
assign tmp_8_fu_182_p2 = (tmp_data_V_reg_78 > opB_assign_reg_88? 1'b1: 1'b0);
assign tmp_id_V_1_fu_140_p1 = xcelreq_V[10:0];
assign tmp_id_V_2_fu_158_p1 = xcelreq_V[10:0];
assign tmp_id_V_3_fu_216_p1 = xcelreq_V[10:0];
assign tmp_id_V_fu_122_p1 = xcelreq_V[10:0];


endmodule //GcdXcelHLS

